### ISSUE TITLE
Update plugin notice to include plugin name

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-menus#1]
`This plugin requires WordPress 4.7.2 and Genesis 2.4.2, or greater. Please install and activate the latest version of Genesis to use this plugin.`

should say 

Genesis Simple Menus requires WordPress 4.7.2 and Genesis 2.4.2, or greater. Please install and activate the latest version of Genesis to use this plugin.

The other plugins use the plugin name, but if you activate a non- G theme and it says this plugin on the themes page, you can't tell which one.

**Comment by nathanrice** [comment]
8e7952f

**Comment by dreamwhisper** [comment]
`Genesis Simple Menus requires WordPress 4.7.2 and Genesis 2.4.2, or greater. Please install and activate the latest version of Genesis to use this plugin.`
